### ISSUE TITLE
ClientHandler crash

### ISSUE THREAD

**Issue by sentosa** [sjlamerton/wxWebViewChromium#1] opened 2013-02-05 06:23 UTC
When you delete wxWebView class during loading a web-page then sometimes OnLoadEnd will be called from Chromium after ~wxWebViewChromium() was called.

Whend this happens the wxWidgets application crashes.

To test:
wxWebView *webView = wxWebView::New(this, wxID_ANY, _("http://www.blick.ch"), pos, size, wxWebViewBackendChromium);
wxDELETE(webView );

**Comment by sjlamerton** [comment] 2013-02-06 10:28
Thanks for the report, will fix in the next few days.

**Comment by sentosa** [comment] 2013-02-06 16:50
Hi Steven

Thanks a lot.

Question: Why using cef1 and not cef3?

Kind Regards

George

Sent by iPhone on the road.

**Comment by sjlamerton** [comment] 2013-02-09 21:32
Only because when I started cef3 hadn't been developed yet. I would like to update wxWebViewChromium to use it in the future however. 

If you add the following to the top of OnLoadEnd() does it resolve the issue?

```
if(!m_webview)
    return;
```

**Comment by sentosa** [comment] 2013-02-13 07:31
1.) wxWebViewChromium::~wxWebViewChromium() is called
2.) void ClientHandler::OnLoadEnd(CefRefPtr<CefBrowser> browser, CefRefPtr<CefFrame> frame, int WXUNUSED(httpStatusCode))
--> m_webview != NULL
3.) First-chance exception at 0x747fd09c in test.exe: 0xC0000005: Access violation reading location 0xfeeeff26.
Application crash.

**Comment by sjlamerton** [comment] 2013-02-14 18:06
Ok, thanks, how about:

if(!m_webview || m_webview->IsBeingDeleted())
    return;

**Comment by sentosa** [comment] 2013-02-14 19:49
1.) wxWebViewChromium::~wxWebViewChromium() is called
2.) void ClientHandler::OnLoadEnd(CefRefPtr browser, CefRefPtr frame, int WXUNUSED(httpStatusCode))
3.) if(!m_webview || m_webview->IsBeingDeleted())
     return;
--> it returns, Ok.
But application still crashes. 
First-chance exception at 0x00d823a8 in test.exe: 0xC0000005: Access violation reading location 0xfeeefeee.
Crash probably comes from insides cef1 because handler not unregistered?
Any idea to unregister/shutdown cef1?
Please note that this does not happen with simple html pages. It only happens with compex news pages like http://www.blick.ch

**Comment by sentosa** [comment] 2013-02-14 20:37
![crash](https://f.cloud.github.com/assets/3478721/158413/0c76fa5a-76e6-11e2-8731-014bbce19b9d.png)
Here it crashes after deleting wxWebViewChromium.

**Comment by sjlamerton** [comment] 2013-02-14 21:16
Thanks for the screenshot, I will have to take a look into this more deeply.

**Comment by sentosa** [comment] 2013-02-15 06:59
Try the following and let it run some minutes. Timer is set to 20 seconds.

```
wxWebView *m_webView = NULL;

void mainwndclass::OnTimer(wxTimerEvent&)
{
  wxSize size(1440, 900);
  wxPoint point(0,0);

  if(!m_webView)
  {
      m_webView = wxWebView::New(this, wxID_ANY, _T("http://www.blick.ch"), point, size,   wxWebViewBackendChromium);
  }
  else
  {
    wxDELETE(m_webView);
  }
}
```

you see that it gets first an exception and then a crash...

**Comment by sjlamerton** [comment] 2013-02-17 18:52
Thanks, with your example I can reproduce this properly now. I will hopefully have some time to look at this in the next week.

**Comment by sjlamerton** [comment] 2013-02-19 16:48
I just pushed a branch that fixes the issue for me. Can you test and let me know? Thanks!

**Comment by sentosa** [comment] 2013-02-20 09:01
With the timer approach I get exceptions in CefDoMessageLoopWork(); and debugger writes:
ASSERTION FAILED: !jsEvent.IsEmpty()
test.exe has triggered a breakpoint
test.exe has triggered a breakpoint
ASSERTION FAILED: m_ptr
test.exe has triggered a breakpoint
test.exe has triggered a breakpoint
ASSERTION FAILED: m_ptr
It looks like it is cef1.1180.832... probably cef3.1364.1094 would solve it.
if I use www.bbc.co.uk I get full crash even in cefclient sample cef1.1180.832 but cefclientsample  cef3.1364.1094 works...

**Comment by sjlamerton** [comment] 2013-02-20 18:45
I agree, I think that it is probably a cef1.1180.832 issues so I'll close this for now, the initial issue should be fixed with my latest commit. Feel free to open another issue if you find anything else, thanks for reporting it.

**Closed as completed by sjlamerton** 2013-02-20 18:45 UTC
Labels: bug
